[2024-07-11T19:06:01.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T19:06:01.585+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T19:05:53.575501+00:00 [queued]>
[2024-07-11T19:06:01.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T19:05:53.575501+00:00 [queued]>
[2024-07-11T19:06:01.598+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-11T19:06:01.626+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-11 19:05:53.575501+00:00
[2024-07-11T19:06:01.634+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T19:06:01.637+0000] {standard_task_runner.py:63} INFO - Started process 806 to run task
[2024-07-11T19:06:01.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ny_tlc_drivers_app', 'transform_data', 'manual__2024-07-11T19:05:53.575501+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/ny_tlc_drivers.py', '--cfg-path', '/tmp/tmp2m38qij1']
[2024-07-11T19:06:01.639+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask transform_data
[2024-07-11T19:06:01.718+0000] {task_command.py:426} INFO - Running <TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T19:05:53.575501+00:00 [running]> on host 0c05e79c8db4
[2024-07-11T19:06:01.912+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_tlc_drivers_app' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T19:05:53.575501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T19:05:53.575501+00:00'
[2024-07-11T19:06:01.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T19:06:01.919+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T19:06:01.920+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-11T19:06:01.939+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ny_tlc_drivers_app, task_id=transform_data, run_id=manual__2024-07-11T19:05:53.575501+00:00, execution_date=20240711T190553, start_date=20240711T190601, end_date=20240711T190601
[2024-07-11T19:06:01.963+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task transform_data (too many values to unpack (expected 2); 806)
[2024-07-11T19:06:01.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T19:06:02.026+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T19:06:02.030+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
