[2024-07-11T21:08:55.778+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T21:08:55.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:08:40+00:00 [queued]>
[2024-07-11T21:08:55.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:08:40+00:00 [queued]>
[2024-07-11T21:08:55.824+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-11T21:08:55.846+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-11 21:08:40+00:00
[2024-07-11T21:08:55.854+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1509) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T21:08:55.858+0000] {standard_task_runner.py:63} INFO - Started process 1511 to run task
[2024-07-11T21:08:55.857+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ny_tlc_drivers_app', 'transform_data', 'manual__2024-07-11T21:08:40+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/ny_tlc_drivers.py', '--cfg-path', '/tmp/tmptuv2c_80']
[2024-07-11T21:08:55.859+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask transform_data
[2024-07-11T21:08:55.923+0000] {task_command.py:426} INFO - Running <TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:08:40+00:00 [running]> on host 0c05e79c8db4
[2024-07-11T21:08:56.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_tlc_drivers_app' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T21:08:40+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T21:08:40+00:00'
[2024-07-11T21:08:56.086+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T21:08:56.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T21:08:56.090+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform.py", line 13, in transform_data
    raise ValueError("Input data is not a DataFrame")
ValueError: Input data is not a DataFrame
[2024-07-11T21:08:56.108+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ny_tlc_drivers_app, task_id=transform_data, run_id=manual__2024-07-11T21:08:40+00:00, execution_date=20240711T210840, start_date=20240711T210855, end_date=20240711T210856
[2024-07-11T21:08:56.127+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task transform_data (Input data is not a DataFrame; 1511)
[2024-07-11T21:08:56.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T21:08:56.190+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T21:08:56.194+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
